apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictNamespaces
metadata:
  name: restrict-ns
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    restrictedNamespaces: ["geo"]
