apiVersion: networking.istio.io/v1beta1
kind: VirtualService                       #canary-release or traffic splitting or A/B Testing example
metadata:
  name: vets-service-route-1
  namespace: default
spec:
  hosts:
  - vets-service
  http: #match,route,fault,reties,timeout
  - route:
    - destination:
        host: vets-service
        subset: v1
      weight: 95
    - destination:
        host: vets-service
        subset: v2
      weight: 5

---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: vets-service-destination
  namespace: default
spec:
  host: vets-service 
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
